services:
  postgres:
    container_name: postgres-sql-wac
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: groundtruth_clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - GroundTruth
    restart: unless-stopped
  app:
    container_name: groundtruth-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sql-wac:5432/groundtruth_clone
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - GroundTruth
    restart: unless-stopped

networks:
  GroundTruth:
    driver: bridge

volumes:
  postgres:
    driver: local
