services:
  postgres:
    container_name: postgres-sql-wac
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: groundtruth_clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - GroundTruth
    restart: unless-stopped

networks:
  GroundTruth:
    driver: bridge

volumes:
  postgres:
    driver: local
